

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redisimp
    password: happy123
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: redisImplementation
  redis:
    port: 6379
    password: password
    host: localhost
server:
  port: 5000

